version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 607560545916.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t nodeimages . 
      - echo Pushing Docker image to ECR...
      - docker tag nodeimages:latest 607560545916.dkr.ecr.us-east-1.amazonaws.com/nodeimages:latest 
      - docker push 607560545916.dkr.ecr.us-east-1.amazonaws.com/nodeimages:latest 
  post_build:
    commands:
      - echo Build completed on date
      - echo Creating image definitions file...
      - echo '[{"name":"rohitnodeapp","imageUri":"607560545916.dkr.ecr.us-east-1.amazonaws.com/nodeimages","containerPort":3000}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json
