version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r8u4k8a1 
  build:
    commands:
      - echo Building Docker image...
      - docker build -t nodeimages . 
      - echo Pushing Docker image to ECR...
      - docker tag nodeimages:latest public.ecr.aws/r8u4k8a1/nodeimages:latest 
      - docker push public.ecr.aws/r8u4k8a1/nodeimages:latest 
  post_build:
    commands:
      - echo Build completed on date
      - echo Creating image definitions file...
      - echo '[{"name":"rohitnodeapp","imageUri":"public.ecr.aws/r8u4k8a1/nodeimages","containerPort":3000}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json
